name: GalerkaAuthPlugin
version: '${version}'
main: org.justiks.galerkaAuthPlugin.GalerkaAuthPlugin
api-version: '26.1'
load: POSTWORLD
description: Плагин авторизации с SQLite

commands:
  logout:
    description: Выход из аккаунта
    usage: /logout

permissions:
  galerkaauth.admin.unregister:
    description: Удаление аккаунтов игроков
    default: op
  galerkaauth.*:
    description: Все права плагина
    default: op
    children:
      galerkaauth.admin.unregister: true
